import { DistrictData, IncidentMarker, HeatPoint } from './types';

// Real Geographic Lat/Lng for Karnataka State Districts
export const KARNATAKA_DISTRICTS: DistrictData[] = [
  {
    id: 'bengaluru_urban',
    name: 'Bengaluru Urban',
    code: 'BLRU',
    latLng: [12.9716, 77.5946],
    activeCasesCount: 88,
    crimeDensity: 'High',
    riskScore: 96,
    primaryCrimeType: 'Cyber Heist & House Burglary',
    commandingOfficer: 'CP B Dayananda (IPS)',
    policeStations: 112,
  },
  {
    id: 'bengaluru_rural',
    name: 'Bengaluru Rural',
    code: 'BLRR',
    latLng: [13.2257, 77.5750],
    activeCasesCount: 29,
    crimeDensity: 'Medium',
    riskScore: 71,
    primaryCrimeType: 'Highway Logistics Theft',
    commandingOfficer: 'SP Mallikarjun Baldandi',
    policeStations: 24,
  },
  {
    id: 'mysuru',
    name: 'Mysuru',
    code: 'MYS',
    latLng: [12.2958, 76.6394],
    activeCasesCount: 46,
    crimeDensity: 'High',
    riskScore: 87,
    primaryCrimeType: 'Heritage Theft & Cyber Fraud',
    commandingOfficer: 'CP Seema Latkar',
    policeStations: 44,
  },
  {
    id: 'belagavi',
    name: 'Belagavi',
    code: 'BGM',
    latLng: [15.8497, 74.4977],
    activeCasesCount: 39,
    crimeDensity: 'High',
    riskScore: 84,
    primaryCrimeType: 'Organized Crime & Syndicate',
    commandingOfficer: 'IGP Borase N',
    policeStations: 48,
  },
  {
    id: 'kalaburagi',
    name: 'Kalaburagi',
    code: 'KLB',
    latLng: [17.3297, 76.8343],
    activeCasesCount: 28,
    crimeDensity: 'High',
    riskScore: 78,
    primaryCrimeType: 'Property Offence',
    commandingOfficer: 'DCP Isha Pant',
    policeStations: 32,
  },
  {
    id: 'dharwad',
    name: 'Dharwad',
    code: 'DWD',
    latLng: [15.3647, 75.1240],
    activeCasesCount: 32,
    crimeDensity: 'High',
    riskScore: 81,
    primaryCrimeType: 'Student & Commercial Fraud',
    commandingOfficer: 'CP N Shashi Kumar',
    policeStations: 30,
  },
  {
    id: 'dakshina_kannada',
    name: 'Dakshina Kannada',
    code: 'DKN',
    latLng: [12.9141, 74.8560],
    activeCasesCount: 42,
    crimeDensity: 'High',
    riskScore: 89,
    primaryCrimeType: 'Cyber Crime & Port Smuggling',
    commandingOfficer: 'CP Anupam Agrawal',
    policeStations: 41,
  },
  {
    id: 'shivamogga',
    name: 'Shivamogga',
    code: 'SMG',
    latLng: [13.9299, 75.5681],
    activeCasesCount: 24,
    crimeDensity: 'Medium',
    riskScore: 65,
    primaryCrimeType: 'Communal Disturbance / Tech Cyber',
    commandingOfficer: 'SP Mithun Kumar GK',
    policeStations: 28,
  },
  {
    id: 'tumakuru',
    name: 'Tumakuru',
    code: 'TMK',
    latLng: [13.3379, 77.1173],
    activeCasesCount: 35,
    crimeDensity: 'High',
    riskScore: 82,
    primaryCrimeType: 'Industrial Theft & Highway Gangs',
    commandingOfficer: 'SP Ashok KV',
    policeStations: 38,
  },
  {
    id: 'ballari',
    name: 'Ballari',
    code: 'BLR',
    latLng: [15.1394, 76.9214],
    activeCasesCount: 31,
    crimeDensity: 'High',
    riskScore: 83,
    primaryCrimeType: 'Economic & Mining Offence',
    commandingOfficer: 'SP Ranjit Kumar Bandaru',
    policeStations: 35,
  },
  {
    id: 'vijayapura',
    name: 'Vijayapura',
    code: 'VJP',
    latLng: [16.8302, 75.7100],
    activeCasesCount: 21,
    crimeDensity: 'Medium',
    riskScore: 68,
    primaryCrimeType: 'Illegal Firearm Trafficking',
    commandingOfficer: 'SP Anupam Agarwal',
    policeStations: 26,
  },
  {
    id: 'bidar',
    name: 'Bidar',
    code: 'BDR',
    latLng: [17.9104, 77.5199],
    activeCasesCount: 14,
    crimeDensity: 'Medium',
    riskScore: 62,
    primaryCrimeType: 'Border Smuggling',
    commandingOfficer: 'SP Pradeep Kumar',
    policeStations: 18,
  },
  {
    id: 'yadgir',
    name: 'Yadgir',
    code: 'YDG',
    latLng: [16.7700, 77.1300],
    activeCasesCount: 11,
    crimeDensity: 'Low',
    riskScore: 45,
    primaryCrimeType: 'Land Dispute',
    commandingOfficer: 'SP Sangeetha G',
    policeStations: 14,
  },
  {
    id: 'bagalkote',
    name: 'Bagalkote',
    code: 'BGK',
    latLng: [16.1804, 75.6961],
    activeCasesCount: 16,
    crimeDensity: 'Low',
    riskScore: 52,
    primaryCrimeType: 'Agricultural Offence',
    commandingOfficer: 'SP Lokesh B',
    policeStations: 22,
  },
  {
    id: 'uttara_kannada',
    name: 'Uttara Kannada',
    code: 'UKN',
    latLng: [14.8080, 74.1300],
    activeCasesCount: 15,
    crimeDensity: 'Low',
    riskScore: 48,
    primaryCrimeType: 'Forest & Coastal Offence',
    commandingOfficer: 'SP Vishnuvardhan N',
    policeStations: 24,
  },
  {
    id: 'udupi',
    name: 'Udupi',
    code: 'UDP',
    latLng: [13.3409, 74.7421],
    activeCasesCount: 19,
    crimeDensity: 'Medium',
    riskScore: 58,
    primaryCrimeType: 'Coastal Cyber Fraud',
    commandingOfficer: 'SP Dr. K Arun',
    policeStations: 21,
  },
  {
    id: 'gadag',
    name: 'Gadag',
    code: 'GDG',
    latLng: [15.4319, 75.6318],
    activeCasesCount: 12,
    crimeDensity: 'Low',
    riskScore: 44,
    primaryCrimeType: 'Property Theft',
    commandingOfficer: 'SP B S Nemagouda',
    policeStations: 16,
  },
  {
    id: 'koppal',
    name: 'Koppal',
    code: 'KPL',
    latLng: [15.3503, 76.1524],
    activeCasesCount: 18,
    crimeDensity: 'Medium',
    riskScore: 59,
    primaryCrimeType: 'Heritage Theft',
    commandingOfficer: 'SP Yashodha Vantagodi',
    policeStations: 19,
  },
  {
    id: 'haveri',
    name: 'Haveri',
    code: 'HVR',
    latLng: [14.7958, 75.3992],
    activeCasesCount: 17,
    crimeDensity: 'Medium',
    riskScore: 56,
    primaryCrimeType: 'Highway Robbery',
    commandingOfficer: 'SP Shivakumar Gunare',
    policeStations: 22,
  },
  {
    id: 'davanagere',
    name: 'Davanagere',
    code: 'DVG',
    latLng: [14.4644, 75.9218],
    activeCasesCount: 20,
    crimeDensity: 'Medium',
    riskScore: 61,
    primaryCrimeType: 'Vehicle Theft',
    commandingOfficer: 'SP Uma Prashanth',
    policeStations: 25,
  },
  {
    id: 'chitradurga',
    name: 'Chitradurga',
    code: 'CTA',
    latLng: [14.2251, 76.3980],
    activeCasesCount: 22,
    crimeDensity: 'Medium',
    riskScore: 64,
    primaryCrimeType: 'National Highway Theft',
    commandingOfficer: 'SP Dharmendra Kumar',
    policeStations: 27,
  },
  {
    id: 'chikkamagaluru',
    name: 'Chikkamagaluru',
    code: 'CKM',
    latLng: [13.3161, 75.7720],
    activeCasesCount: 16,
    crimeDensity: 'Low',
    riskScore: 49,
    primaryCrimeType: 'Encroachment & Wildlife',
    commandingOfficer: 'SP Vikram Amathe',
    policeStations: 23,
  },
  {
    id: 'hassan',
    name: 'Hassan',
    code: 'HSN',
    latLng: [13.0033, 76.1004],
    activeCasesCount: 23,
    crimeDensity: 'Medium',
    riskScore: 63,
    primaryCrimeType: 'Highway Transit Offence',
    commandingOfficer: 'SP Mohammed Suitha',
    policeStations: 29,
  },
  {
    id: 'ramanagara',
    name: 'Ramanagara',
    code: 'RMG',
    latLng: [12.7159, 77.2812],
    activeCasesCount: 22,
    crimeDensity: 'Medium',
    riskScore: 66,
    primaryCrimeType: 'Expressway Robbery',
    commandingOfficer: 'SP Karthik Reddy',
    policeStations: 22,
  },
  {
    id: 'mandya',
    name: 'Mandya',
    code: 'MND',
    latLng: [12.5218, 76.8951],
    activeCasesCount: 21,
    crimeDensity: 'Medium',
    riskScore: 60,
    primaryCrimeType: 'Agricultural Fraud',
    commandingOfficer: 'SP N Yathish',
    policeStations: 27,
  },
  {
    id: 'chamarajanagara',
    name: 'Chamarajanagara',
    code: 'CMR',
    latLng: [11.9261, 76.9437],
    activeCasesCount: 14,
    crimeDensity: 'Low',
    riskScore: 47,
    primaryCrimeType: 'Forest Poaching & Inter-state',
    commandingOfficer: 'SP Padmini Sahoo',
    policeStations: 18,
  },
  {
    id: 'kodagu',
    name: 'Kodagu',
    code: 'KDG',
    latLng: [12.4244, 75.7382],
    activeCasesCount: 13,
    crimeDensity: 'Low',
    riskScore: 42,
    primaryCrimeType: 'Plantation Dispute',
    commandingOfficer: 'SP K Ramarajan',
    policeStations: 16,
  },
  {
    id: 'chikkaballapura',
    name: 'Chikkaballapura',
    code: 'CBP',
    latLng: [13.4355, 77.7279],
    activeCasesCount: 18,
    crimeDensity: 'Medium',
    riskScore: 59,
    primaryCrimeType: 'Airport Highway Hijack',
    commandingOfficer: 'SP DL Nagesh',
    policeStations: 20,
  },
  {
    id: 'kolar',
    name: 'Kolar',
    code: 'KLR',
    latLng: [13.1367, 78.1292],
    activeCasesCount: 25,
    crimeDensity: 'Medium',
    riskScore: 69,
    primaryCrimeType: 'Gold & Mineral Theft',
    commandingOfficer: 'SP M Narayana',
    policeStations: 26,
  }
];

export const INITIAL_INCIDENTS: IncidentMarker[] = [
  {
    id: 'inc-0456',
    firNumber: 'FIR KRP/2026/0456',
    title: 'Anekal Residence Armed Burglary',
    category: 'active',
    districtId: 'bengaluru_urban',
    districtName: 'Bengaluru Urban',
    latLng: [12.8050, 77.6980],
    timestamp: '14 mins ago',
    severity: 'CRITICAL',
    ioName: 'Inspector Arjun Kumar',
    status: 'AFIS Fingerprint Matched (89%)',
    summary: 'Jewelry stolen at gunpoint. Suspect vehicle KA-03-MN-4491 tracked near Hosur main road.'
  },
  {
    id: 'inc-0892',
    firNumber: 'FIR MYS/2026/0892',
    title: 'Devaraja Market Online Heist',
    category: 'cyber',
    districtId: 'mysuru',
    districtName: 'Mysuru',
    latLng: [12.3080, 76.6530],
    timestamp: '32 mins ago',
    severity: 'HIGH',
    ioName: 'Sub-Inspector Radhika',
    status: 'Mule Accounts Frozen',
    summary: '₹48 Lakhs diverted via spoofed UPI gateway. IP traced to Jamtara proxy network.'
  },
  {
    id: 'inc-1042',
    firNumber: 'FIR BGM/2026/1042',
    title: 'Border Highway Illegal Arms Smuggling',
    category: 'organized',
    districtId: 'belagavi',
    districtName: 'Belagavi',
    latLng: [15.8600, 74.5080],
    timestamp: '1 hour ago',
    severity: 'CRITICAL',
    ioName: 'DySP Ramesh Patil',
    status: 'Inter-state Checkpost Alert',
    summary: 'Custom 9mm pistols seized from truck concealed under sugarcane cargo.'
  },
  {
    id: 'inc-0311',
    firNumber: 'FIR DKN/2026/0311',
    title: 'Panambur Port Smuggling Cartel',
    category: 'critical',
    districtId: 'dakshina_kannada',
    districtName: 'Dakshina Kannada',
    latLng: [12.9500, 74.8050],
    timestamp: '2 hours ago',
    severity: 'CRITICAL',
    ioName: 'ACP Vijayendra',
    status: 'Coast Guard Radar Ingesting',
    summary: 'Contraband vessel intercepted 12 nautical miles off Mangaluru port.'
  },
  {
    id: 'inc-0520',
    firNumber: 'FIR DWD/2026/0520',
    title: 'Unkal Lake ATM Robbery Syndicate',
    category: 'active',
    districtId: 'dharwad',
    districtName: 'Dharwad (Hubballi)',
    latLng: [15.3700, 75.1300],
    timestamp: '3 hours ago',
    severity: 'HIGH',
    ioName: 'Inspector Mahesh',
    status: 'LPR Camera Match',
    summary: 'Gas cutter gang breached ATM vault. LPR matched getaway Bolero.'
  },
  {
    id: 'inc-0711',
    firNumber: 'FIR TMK/2026/0711',
    title: 'National Highway 48 Cargo Hijack',
    category: 'active',
    districtId: 'tumakuru',
    districtName: 'Tumakuru',
    latLng: [13.3450, 77.1250],
    timestamp: '4 hours ago',
    severity: 'HIGH',
    ioName: 'Inspector Balaram',
    status: 'GPS Beacon Live',
    summary: 'Electronics consignment truck intercepted. Signal tracked near Sira bypass.'
  },
  {
    id: 'inc-0990',
    firNumber: 'FIR BLR/2026/0990',
    title: 'Kudligi Mining Equipment Extortion',
    category: 'organized',
    districtId: 'ballari',
    districtName: 'Ballari',
    latLng: [15.1500, 76.9300],
    timestamp: '5 hours ago',
    severity: 'MEDIUM',
    ioName: 'DySP Srinivas',
    status: 'Under Surveillance',
    summary: 'Extortion calls made to mining operators. Voice print match 94% with syndicate leader.'
  },
  {
    id: 'inc-0128',
    firNumber: 'FIR SMG/2026/0128',
    title: 'Agumbe Ghat Missing Hiker Search',
    category: 'active',
    districtId: 'shivamogga',
    districtName: 'Shivamogga',
    latLng: [13.5080, 75.0920],
    timestamp: '6 hours ago',
    severity: 'MEDIUM',
    ioName: 'PSI Girish',
    status: 'Drone Infrared Search Active',
    summary: 'Last cellular ping recorded at 04:12 PM near Sunset Point tower.'
  },
  {
    id: 'inc-0044',
    firNumber: 'FIR KLB/2026/0044',
    title: 'Jewelry Shop Vault Breach',
    category: 'closed',
    districtId: 'kalaburagi',
    districtName: 'Kalaburagi',
    latLng: [17.3400, 76.8400],
    timestamp: '1 day ago',
    severity: 'LOW',
    ioName: 'Inspector Venkatesh',
    status: 'Form 173 Chargesheet Submitted',
    summary: 'All 3 suspects arrested with 100% stolen gold recovered.'
  }
];

export const HEATMAP_POINTS: HeatPoint[] = [
  { latLng: [12.9716, 77.5946], intensity: 0.95, radius: 25000, type: 'Property Crime' },
  { latLng: [13.2257, 77.5750], intensity: 0.60, radius: 18000, type: 'Highway Crime' },
  { latLng: [12.2958, 76.6394], intensity: 0.85, radius: 20000, type: 'Cyber Crime' },
  { latLng: [15.8497, 74.4977], intensity: 0.75, radius: 22000, type: 'Organized Crime' },
  { latLng: [12.9141, 74.8560], intensity: 0.90, radius: 24000, type: 'Narcotics & Smuggling' },
  { latLng: [15.3647, 75.1240], intensity: 0.80, radius: 19000, type: 'ATM Theft' },
  { latLng: [13.3379, 77.1173], intensity: 0.70, radius: 18000, type: 'Highway Theft' },
  { latLng: [15.1394, 76.9214], intensity: 0.65, radius: 17000, type: 'Mining Offence' },
  { latLng: [17.3297, 76.8343], intensity: 0.55, radius: 16000, type: 'Vault Breach' },
  { latLng: [13.1367, 78.1292], intensity: 0.50, radius: 15000, type: 'Highway Transit' }
];
